version: '2'

networks:
    desafio:
services:
    mysql:
        image: mysql
        container_name: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: desafio
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            desafio:
                aliases: 
                    - mysql
                    
    webserver:
        image: nginx:alpine
        container_name: nginx
        working_dir: /application
        volumes:
            - ./backend:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            desafio:
                aliases: 
                    - webserver
                    
    php-fpm:
        build: phpdocker/php-fpm
        container_name: php
        working_dir: /application
        volumes:
            - ./backend:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini        
        networks:
            desafio:
                aliases:
                    - php-fpm
    # angular:
        # container_name: angular  
        # build: ./frontend
        # volumes:
            # - './frontend:/usr/src/app' 
        # ports:
            # - '4200:4200'
        # command: bash -c "npm install && ng serve --host angular --port 4200"        
        # networks:
            # desafio:
                # aliases: 
                    # - angular